# Generated by Django 3.1.3 on 2022-12-18 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_store_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='cost',
            field=models.FloatField(default=100.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='discount',
            field=models.FloatField(default=0.8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='price',
            field=models.FloatField(default=100.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='specification',
            field=models.CharField(default='红富市1.02', max_length=100),
            preserve_default=False,
        ),
    ]
