# Generated by Django 3.1.3 on 2023-06-12 11:37

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bx_clbx',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('报销人', models.CharField(blank=True, max_length=255, null=True)),
                ('部门', models.CharField(blank=True, max_length=255, null=True)),
                ('是否享受车改', models.BooleanField(default=False)),
                ('是否公派车辆', models.BooleanField(default=False)),
                ('事由', models.CharField(blank=True, max_length=255, null=True)),
                ('行项目', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'db_table': '差旅报销',
                'managed': True,
            },
        ),
    ]
