# Generated by Django 3.1.3 on 2023-06-15 12:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('article_bx', '0002_bx_clbx_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='bx_clbx',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='bx_clbx',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
